-- create table chef (id bigint generated by default as identity, firstname varchar(255), lastname varchar(255), primary key (id))
INSERT INTO  chef (firstname, lastname) VALUES ('Konrad', 'Ott');

-- create table store (id bigint generated by default as identity, store_key varchar(255), store_type integer, chef_id bigint, primary key (id))
INSERT INTO store (store_key, store_type, chef_id)
VALUES ('Sample Store 1', 0, 1), ('Sample Store 2', 1, 1), ('Sample Store 3', 1, 1);

-- create table car (id bigint generated by default as identity, available boolean not null, badge varchar(255), store_id bigint, primary key (id))
INSERT INTO car (available, badge, store_id) VALUES
  (TRUE, 'A-BC-001', 1),
  (TRUE, 'A-BC-002', 1),
  (TRUE, 'A-BC-003', 2),
  (TRUE, 'A-BC-004', 2),
  (TRUE, 'A-BC-005', 3),
  (TRUE, 'A-BC-006', 3),
  (TRUE, 'A-BC-007', 1),
  (TRUE, 'A-BC-008', 2),
  (TRUE, 'A-BC-009', 3);

-- create table driver (id bigint generated by default as identity, birthDay date, firstname varchar(25), lastname varchar(25), store_id bigint, primary key (id))
INSERT INTO driver (birthDay, firstname, lastname, store_id)
VALUES
  (CURDATE(), 'Konrad', 'Öttl', 1),
  (CURDATE(), 'Sven', 'Klemmer', 1),
  (CURDATE(), 'Sample', 'Driver 1', 2),
  (CURDATE(), 'Sample', 'Driver 2', 2),
  (CURDATE(), 'Sample', 'Driver 3', 3),
  (CURDATE(), 'Sample', 'Driver 4', 3),
  (CURDATE(), 'Sample', 'Driver 5', 1),
  (CURDATE(), 'Sample', 'Driver 6', 2),
  (CURDATE(), 'Sample', 'Driver 7', 3);


-- create table invoice (id bigint generated by default as identity, date date, income double, state integer, car_id bigint, driver_id bigint, store_id bigint, primary key (id))
INSERT INTO invoice (date, income, state, car_id, driver_id, store_id) VALUES
  (CURDATE(), 111.01, 0, 1, 9, 1),
  (CURDATE(), 222.20, 0, 2, 8, 2),
  (CURDATE(), 333.03, 0, 3, 7, 3),
  (CURDATE(), 444.40, 0, 4, 6, 1),
  (CURDATE(), 555.05, 0, 5, 5, 2),
  (CURDATE(), 666.60, 0, 6, 4, 3),
  (CURDATE(), 777.07, 0, 7, 3, 1),
  (CURDATE(), 888.80, 0, 8, 2, 2),
  (CURDATE(), 999.09, 0, 9, 1, 3);

-- create table invoice_bill (Invoice_id bigint not null, bills double)
INSERT INTO invoice_bill VALUES
  (1, 50.0),
  (2, 25.23),
  (2, 12.23),
  (4, 76.10),
  (7, 37.45);

-- create table invoice_ec (Invoice_id bigint not null, ecpayment double)
INSERT INTO invoice_ec VALUES
  (1, 9.49),
  (1, 21.50),
  (2, 4.99),
  (2, 5.99),
  (3, 6.00),
  (3, 14.35),
  (4, 56.02),
  (4, 100.23),
  (5, 9.49),
  (5, 21.50),
  (6, 4.99),
  (6, 5.99),
  (7, 6.00),
  (7, 14.35),
  (8, 5.23),
  (8, 14.00);

INSERT INTO users VALUES
  (1, CURDATE(), 'admin@admin.de', 'admin', 'password'),
  (2, CURDATE(), 'fahrer@admin.de', 'fahrer', 'password'),
  (3, CURDATE(), 'chef@admin.de', 'chef', 'password');

INSERT INTO roles VALUES
  (1, 'ROLE_ADMIN', 1),
  (2, 'ROLE_FAHRER', 1),
  (3, 'ROLE_CHEF', 1),
  (4, 'ROLE_FAHRER', 2),
  (5, 'ROLE_CHEF', 3);



-- alter table car add constraint FK_6qp4slmsfm0lljs5n739f7a5y foreign key (store_id) references store
-- alter table car add constraint FK_6r8o3eus6g1msrmkavs8pwm84 foreign key (id) references store
-- alter table driver add constraint FK_7261aallghqy6u8eoykjkcts7 foreign key (store_id) references store
-- alter table driver add constraint FK_h0dq8jcces3yuqjwtuethjqip foreign key (id) references store
-- alter table invoice add constraint FK_9d9rnelsj39poj8oodalfkovb foreign key (car_id) references car
-- alter table invoice add constraint FK_homyv82noqsm5i0ra2rue5tmm foreign key (driver_id) references driver
-- alter table invoice add constraint FK_jgalq93ui9d1f5cxbdjm0sj2w foreign key (store_id) references store
-- alter table invoice add constraint FK_apeohlmard0igdlx6cch1mycp foreign key (id) references store
-- alter table invoice_bill add constraint FK_ebqbb501l7fbtuo1sd66pdfyq foreign key (Invoice_id) references invoice
-- alter table invoice_ec add constraint FK_q6xeomo93eea0mblsadq2c9sv foreign key (Invoice_id) references invoice
-- alter table store add constraint FK_9p25m2x1reunmwk9ua5k65pd1 foreign key (chef_id) references chef
-- alter table store add constraint FK_84ngjmvfdrewjc127xa8cxid7 foreign key (id) references chef
